# Generated by Django 2.0 on 2020-06-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comeback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Música')),
                ('data', models.DateField(verbose_name='Data do Comeback')),
                ('views', models.PositiveIntegerField(verbose_name='Número de Views')),
                ('likes', models.PositiveIntegerField(verbose_name='Número de Likes')),
                ('deslikes', models.PositiveIntegerField(verbose_name='Número de Deslikes')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Grupo')),
                ('debut', models.DateField(verbose_name='Debut do Grupo')),
                ('resumo', models.TextField(verbose_name='Resumo do Grupo')),
                ('imagem', models.ImageField(upload_to='', verbose_name='Foto do Grupo')),
            ],
        ),
    ]
