# Generated by Django 2.0 on 2020-06-11 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0002_comeback_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comeback',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='grupos.Grupo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='integrante',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='grupos.Grupo'),
            preserve_default=False,
        ),
    ]
