# Generated by Django 3.0.7 on 2020-06-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grupos', '0004_auto_20200611_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comeback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Música')),
                ('data', models.DateField(verbose_name='Data do Comeback')),
                ('views', models.PositiveIntegerField(verbose_name='Número de Views')),
                ('likes', models.PositiveIntegerField(verbose_name='Número de Likes')),
                ('deslikes', models.PositiveIntegerField(verbose_name='Número de Deslikes')),
            ],
        ),
    ]
