# Generated by Django 3.0.7 on 2020-06-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0005_comeback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Grupo')),
                ('debut', models.DateField(verbose_name='Debut do Grupo')),
                ('resumo', models.TextField(verbose_name='Resumo do Grupo')),
                ('imagem', models.ImageField(upload_to='', verbose_name='Foto do Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Integrante')),
                ('idade', models.PositiveIntegerField(verbose_name='Idade da Integrante')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=2)),
                ('pais', models.CharField(max_length=100, verbose_name='País da Integrante')),
                ('imagem', models.ImageField(upload_to='', verbose_name='Foto da Integrante')),
            ],
        ),
    ]
